### ISSUE TITLE
Upstream changes in three.js shader conventions (via aframe 1.2.0)

### ISSUE THREAD

**Issue by esi-jwr** [nikolaiwarner/aframe-chromakey-material#4]
Dear all,

 upgrading to a recent release of aframe leads to error messages when evaluating the chromykey fragment shader. This is due to ThreeJS.ShaderMaterial expecting glsl 3 level code now, in which 'texture' is a function name, thus cannot be used as a variable any longer. 

 Here's a similar problem and discussion: https://github.com/mrdoob/three.js/issues/19627

 For anyone looking for a quick fix: simply changing the variable name for the texture2d uniform in the fragmentShader to eg. 'myTexture', then reflecting the change in the ShaderMaterial binding code fixes the problem. 

 Best regards,
Jan

**Comment by synth** [comment]
@nikolaiwarner ^ Made a PR for this quick and easy change. The community would appreciate it if it can be merged in! Thanks for this great Aframe component!

**Comment by nikolaiwarner** [comment]
Thanks @synth and @esi-jwr! I've merged @synth's PR to fix this and updated the npm package. Apologies for the slow turnaround on my part with this issue. Thanks again!

**Comment by synth** [comment]
@nikolaiwarner no problem and thanks for merging. Last question: what should we do about the dist/ files? Might be good to update those as well, I would have included them but I don't know how to generate them ;)

**Comment by nikolaiwarner** [comment]
@synth thanks for reminding me! it's just `yarn dist` but while i was doing that i noticed one more thing that needed to be fixed. So I've fixed that and also added an example page to test against. I've published a new version with all the updates needed to support the latest version of aframe and included the minified dist version.

**Comment by synth** [comment]
@nikolaiwarner Rockin! Thank you!
