### ISSUE TITLE
Component seems to not work in AFRAME version 1.2.0

### ISSUE THREAD

**Issue by joao-pratas-eyekandy** [nikolaiwarner/aframe-chromakey-material#7]
Hi there,

It seems like this component is not supported in version 1.2.0 of AFRAME.

I tried using it following the readme file and got this error:

`THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog invalid shaders  THREE.WebGLShader: gl.getShaderInfoLog() fragment
ERROR: 0:96: 'texture' : function name expected
ERROR: 0:96: 'rgb' :  field selection requires structure, vector, or interface block on left hand side
ERROR: 0:96: '=' : dimension mismatch
ERROR: 0:96: '=' : cannot convert from 'const mediump float' to 'highp 3-component vector of float'
1: #version 300 es
2: #define varying in
3: out highp vec4 pc_fragColor;
4: #define gl_FragColor pc_fragColor
5: #define gl_FragDepthEXT gl_FragDepth
6: #define texture2D texture
7: #define textureCube texture
8: #define texture2DProj textureProj
9: #define texture2DLodEXT textureLod
10: #define texture2DProjLodEXT textureProjLod
11: #define textureCubeLodEXT textureLod
12: #define texture2DGradEXT textureGrad
13: #define texture2DProjGradEXT textureProjGrad
14: #define textureCubeGradEXT textureGrad
15: precision highp float;
16: precision highp int;
17: #define HIGH_PRECISION
18: #define SHADER_NAME ShaderMaterial
19: #define GAMMA_FACTOR 2
20: #define USE_SHADOWMAP
21: #define SHADOWMAP_TYPE_PCF
22: uniform mat4 viewMatrix;
23: uniform vec3 cameraPosition;
24: uniform bool isOrthographic;
25: #define DITHERING
26: 
27: vec4 LinearToLinear( in vec4 value ) {
28: 	return value;
29: }
30: vec4 GammaToLinear( in vec4 value, in float gammaFactor ) {
31: 	return vec4( pow( value.rgb, vec3( gammaFactor ) ), value.a );
32: }
33: vec4 LinearToGamma( in vec4 value, in float gammaFactor ) {
34: 	return vec4( pow( value.rgb, vec3( 1.0 / gammaFactor ) ), value.a );
35: }
36: vec4 sRGBToLinear( in vec4 value ) {
37: 	return vec4( mix( pow( value.rgb * 0.9478672986 + vec3( 0.0521327014 ), vec3( 2.4 ) ), value.rgb * 0.0773993808, vec3( lessThanEqual( value.rgb, vec3( 0.04045 ) ) ) ), value.a );
38: }
39: vec4 LinearTosRGB( in vec4 value ) {
40: 	return vec4( mix( pow( value.rgb, vec3( 0.41666 ) ) * 1.055 - vec3( 0.055 ), value.rgb * 12.92, vec3( lessThanEqual( value.rgb, vec3( 0.0031308 ) ) ) ), value.a );
41: }
42: vec4 RGBEToLinear( in vec4 value ) {
43: 	return vec4( value.rgb * exp2( value.a * 255.0 - 128.0 ), 1.0 );
44: }
45: vec4 LinearToRGBE( in vec4 value ) {
46: 	float maxComponent = max( max( value.r, value.g ), value.b );
47: 	float fExp = clamp( ceil( log2( maxComponent ) ), -128.0, 127.0 );
48: 	return vec4( value.rgb / exp2( fExp ), ( fExp + 128.0 ) / 255.0 );
49: }
50: vec4 RGBMToLinear( in vec4 value, in float maxRange ) {
51: 	return vec4( value.rgb * value.a * maxRange, 1.0 );
52: }
53: vec4 LinearToRGBM( in vec4 value, in float maxRange ) {
54: 	float maxRGB = max( value.r, max( value.g, value.b ) );
55: 	float M = clamp( maxRGB / maxRange, 0.0, 1.0 );
56: 	M = ceil( M * 255.0 ) / 255.0;
57: 	return vec4( value.rgb / ( M * maxRange ), M );
58: }
59: vec4 RGBDToLinear( in vec4 value, in float maxRange ) {
60: 	return vec4( value.rgb * ( ( maxRange / 255.0 ) / value.a ), 1.0 );
61: }
62: vec4 LinearToRGBD( in vec4 value, in float maxRange ) {
63: 	float maxRGB = max( value.r, max( value.g, value.b ) );
64: 	float D = max( maxRange / maxRGB, 1.0 );
65: 	D = clamp( floor( D ) / 255.0, 0.0, 1.0 );
66: 	return vec4( value.rgb * ( D * ( 255.0 / maxRange ) ), D );
67: }
68: const mat3 cLogLuvM = mat3( 0.2209, 0.3390, 0.4184, 0.1138, 0.6780, 0.7319, 0.0102, 0.1130, 0.2969 );
69: vec4 LinearToLogLuv( in vec4 value ) {
70: 	vec3 Xp_Y_XYZp = cLogLuvM * value.rgb;
71: 	Xp_Y_XYZp = max( Xp_Y_XYZp, vec3( 1e-6, 1e-6, 1e-6 ) );
72: 	vec4 vResult;
73: 	vResult.xy = Xp_Y_XYZp.xy / Xp_Y_XYZp.z;
74: 	float Le = 2.0 * log2(Xp_Y_XYZp.y) + 127.0;
75: 	vResult.w = fract( Le );
76: 	vResult.z = ( Le - ( floor( vResult.w * 255.0 ) ) / 255.0 ) / 255.0;
77: 	return vResult;
78: }
79: const mat3 cLogLuvInverseM = mat3( 6.0014, -2.7008, -1.7996, -1.3320, 3.1029, -5.7721, 0.3008, -1.0882, 5.6268 );
80: vec4 LogLuvToLinear( in vec4 value ) {
81: 	float Le = value.z * 255.0 + value.w;
82: 	vec3 Xp_Y_XYZp;
83: 	Xp_Y_XYZp.y = exp2( ( Le - 127.0 ) / 2.0 );
84: 	Xp_Y_XYZp.z = Xp_Y_XYZp.y / value.y;
85: 	Xp_Y_XYZp.x = value.x * Xp_Y_XYZp.z;
86: 	vec3 vRGB = cLogLuvInverseM * Xp_Y_XYZp.rgb;
87: 	return vec4( max( vRGB, 0.0 ), 1.0 );
88: }
89: vec4 linearToOutputTexel( vec4 value ) { return LinearToLinear( value ); }
90: 
91: uniform sampler2D texture;
92: uniform vec3 color;
93: varying vec2 vUv;
94: void main(void)
95: {
96: vec3 tColor = texture2D( texture, vUv ).rgb;
97: float a = (length(tColor - color) - 0.5) * 7.0;
98: gl_FragColor = vec4(tColor, a);
99: }`

Is there anyway you could provide some support here?

Much appreciated in advance!

**Comment by sael-you** [comment]
use AFRAME version 1.0.4
`    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
` it's so far the last compatible version, i used this workaround to avoid this error.

**Comment by nikolaiwarner** [comment]
Fixed by #8 to work with the latest Aframe release
